### ISSUE TITLE
사용자의 상태 보기 기능 구현

### ISSUE THREAD

**Issue by JunHyeong-99** [Familing/familing-backend#35]
## description

<img width="326" alt="스크린샷 2024-08-14 오전 9 59 16" src="https://github.com/user-attachments/assets/19b671f3-8561-42a5-88cc-a95c425e3fed">

위 이미지와 같이 사용자의 상태를 설정하고 조회하는 기능을 구현한다.

## Todo

- [x] 우리가족, 자신의 상태 조회하기
- [x] 조회할 때 자신의 상태를 가장 맨 위에 리턴해 프론트가 누가 자신인지 확인할 수 있게한다.

**Comment by jinseohyun1228** [comment]
했어용
?

**Comment by jinseohyun1228** [comment]
> 조회할 때 자신의 상태를 가장 맨 위에 리턴해 프론트가 누가 자신인지 확인할 수 있게한다. 

이거 전반적으로 리팩토링 해야할 것 같아요

**Comment by JunHyeong-99** [comment]
@jinseohyun1228  아뇽 아직 구현 안했습니다!
