### ISSUE TITLE
마이페이지 구현

### ISSUE THREAD

**Issue by jinseohyun1228** [Familing/familing-backend#7]
## description
마이페이지 구현

## Todo
- [x] 프로필 변경 
    - [x] 이름 설정
    - [x] 닉네임 변경
    - [x] 프로필 사진 등록
- [x] 구독 타입
-
## ETC
마이 페이지에 있는 스냅샷 시간 설정 기능은 스냅샷 기능 만들면서 할게요

**Comment by jinseohyun1228** [comment]
@JunHyeong-99 
준형님

json 변환시 스네이크케이스이름 변환을 자동으로 주고 싶어서 application.yml 에 아래 설정 추가해도될까요? 
#  jackson:
#    property-naming-strategy: SNAKE_CASE  <-- 준형님 이거 설정하고 싶은데 문제가 될까요?

**Comment by JunHyeong-99** [comment]
@jinseohyun1228
옹 !! 그런게 있었군요 !! 좋습니다!! 프론트분들이 SNAKE_CASE를 더 좋아하시겠죠??

**Comment by jinseohyun1228** [comment]
아니 저 ... 하다가 좀 이 부분만 구현했어야 하는데 여기저기 너무 많이 건드려버렸어요ㅜㅜㅜ
